package tp6;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gonza
 */
public class ConsultPorPrecio extends javax.swing.JInternalFrame {

    private DefaultTableModel tablaPrecio = new DefaultTableModel();

    /**
     * Creates new form ConsultPorPrecio
     */
    public ConsultPorPrecio() {
        initComponents();
        armarcabecera();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtPrecioMenor = new javax.swing.JTextField();
        jtPrecioMayor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPrecios = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jLabel1.setText("Listado por Precio");

        jLabel2.setText("Entre    $");

        jtPrecioMenor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPrecioMenorKeyReleased(evt);
            }
        });

        jtPrecioMayor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPrecioMayorKeyReleased(evt);
            }
        });

        jLabel3.setText("Y");

        jtPrecios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtPrecios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addComponent(jtPrecioMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(jtPrecioMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtPrecioMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPrecioMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtPrecioMenorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecioMenorKeyReleased
        borrarEscritura();
        try {
            int menor = Integer.parseInt(jtPrecioMenor.getText());
            int mayor = Integer.parseInt(jtPrecioMayor.getText());
            for (Producto pro : Menu_General.lista) {
                if (pro.getPrecio() > menor && pro.getPrecio() < mayor) {
                    tablaPrecio.addRow(new Object[]{
                        pro.getCodigo(),
                        pro.getDescripcion(),
                        pro.getPrecio(),
                        pro.getStock()
                    });
                }
            }
        }catch(NumberFormatException e){
            if(jtPrecioMenor.getText()== null){
                jtPrecioMenor.setText("0");
            }else if(jtPrecioMayor.getText()==null){
                jtPrecioMayor.setText("0");
            }
        }
    }//GEN-LAST:event_jtPrecioMenorKeyReleased

    private void jtPrecioMayorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecioMayorKeyReleased
         borrarEscritura();
        try {
            int menor = Integer.parseInt(jtPrecioMenor.getText());
            int mayor = Integer.parseInt(jtPrecioMayor.getText());
            for (Producto pro : Menu_General.lista) {
                if (pro.getPrecio() >= menor && pro.getPrecio() <= mayor) {
                    tablaPrecio.addRow(new Object[]{
                        pro.getCodigo(),
                        pro.getDescripcion(),
                        pro.getPrecio(),
                        pro.getStock()
                    });
                }
            }
        }catch(NumberFormatException e){
            if(jtPrecioMenor.getText()== null){
                jtPrecioMenor.setText("0");
            }else if(jtPrecioMayor.getText()==null){
                jtPrecioMayor.setText("0");
            }
        }
    }//GEN-LAST:event_jtPrecioMayorKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtPrecioMayor;
    private javax.swing.JTextField jtPrecioMenor;
    private javax.swing.JTable jtPrecios;
    // End of variables declaration//GEN-END:variables

    private void armarcabecera() {
        tablaPrecio.addColumn("Codigo");
        tablaPrecio.addColumn("Descripcion");
        tablaPrecio.addColumn("Precio");
        tablaPrecio.addColumn("Stock");
        jtPrecios.setModel(tablaPrecio);
    }

    private void borrarEscritura(){
        int b=tablaPrecio.getRowCount()-1;
        for(;b>=0;b--){
            tablaPrecio.removeRow(b);
        }
    }
}
